import SIDEExplicitFormula.LiCriterionBridge

/-!
# Axiom audit -- the converse composed: the equality lemma, li_nonneg_iff_rh and arith_limit_nonneg_iff_rh
(act b566, ruling (R176)(3))

Run `lake env lean AxiomCheckLiCriterion.lean` (once the modules are built) to reproduce the `#print axioms` output for
every declaration of `SIDEExplicitFormula/LiCriterionBridge.lean` and for the vendored and kernel terminals it consumes
by name, the `#check` of the two composed theorems, and the `#print` of each definition (the salt-check). Each is
expected to reduce to the standard base (`propext`, `Classical.choice`, `Quot.sound`) or less, with no `sorryAx`. The
compiler`s output is the verdict, not this comment. GENERATED by relay tools/b566_axiomcheck_gen.py from the branch tip.
-/

#print axioms SIDEExplicitFormula.LiCriterionBridge.carrierEquiv
#print axioms SIDEExplicitFormula.LiCriterionBridge.carrierEquiv_val
#print axioms SIDEExplicitFormula.LiCriterionBridge.xi_eq_half_Lambda
#print axioms SIDEExplicitFormula.LiCriterionBridge.analyticOrderAt_xi_eq_zeta
#print axioms SIDEExplicitFormula.LiCriterionBridge.xiMult
#print axioms SIDEExplicitFormula.LiCriterionBridge.zeroMult_eq_xiMult
#print axioms SIDEExplicitFormula.LiCriterionBridge.xiMult_pairedZero
#print axioms SIDEExplicitFormula.LiCriterionBridge.pos_term_eq
#print axioms SIDEExplicitFormula.LiCriterionBridge.neg_term_eq
#print axioms SIDEExplicitFormula.LiCriterionBridge.liReal
#print axioms SIDEExplicitFormula.LiCriterionBridge.LiCoeff_eq_liReal
#print axioms SIDEExplicitFormula.LiCriterionBridge.liReal_summable
#print axioms SIDEExplicitFormula.LiCriterionBridge.li_coeff_eq_taylorCoeff
#print axioms SIDEExplicitFormula.LiCriterionBridge.li_nonneg_iff_rh
#print axioms SIDEExplicitFormula.LiCriterionBridge.arith_limit_nonneg_iff_rh

#print axioms LiCriterion.positivity_implies_RH
#print axioms LiCriterion.taylorCoeff_eq_li_symmetrized
#print axioms LiCriterion.summable_li_symmetrized
#print axioms LiCriterion.rh_equiv_mathlib
#print axioms LiCriterion.liSummand_pairedZero
#print axioms LiCriterion.analyticOrderNatAt_riemannXi_one_sub
#print axioms LiCriterion.pairedZero_involutive
#print axioms XiZeros.xi_eq_half_s_sm1_Lambda
#print axioms SIDEExplicitFormula.LiWeil.rh_imp_li_nonneg
#print axioms SIDEExplicitFormula.LiWeil.li_identity_sym
#print axioms SIDEExplicitFormula.LiWeil.LiCoeff_eq
#print axioms SIDEExplicitFormula.LiWeil.liTerm_re_summable

#check @SIDEExplicitFormula.LiCriterionBridge.li_nonneg_iff_rh
#check @SIDEExplicitFormula.LiCriterionBridge.arith_limit_nonneg_iff_rh
#check @SIDEExplicitFormula.LiCriterionBridge.li_coeff_eq_taylorCoeff

#print SIDEExplicitFormula.LiCriterionBridge.carrierEquiv
#print SIDEExplicitFormula.LiCriterionBridge.xiMult
#print SIDEExplicitFormula.LiCriterionBridge.liReal
