import SIDEExplicitFormula.PageConverses

/-!
# Axiom audit -- the two converses the page lacked (act b569, ruling (R179)(2))

Run `lake env lean AxiomCheckConverses.lean` (once the modules are built) to reproduce the `#print axioms` output for every
declaration of the files below and for the terminals they consume by name, the `#check` of the named statements, and
the `#print` of each definition (the salt-check). Each is expected to reduce to the standard base (`propext`,
`Classical.choice`, `Quot.sound`) or less, with no `sorryAx`. The compiler`s output is the verdict, not this comment.
GENERATED by relay tools/b569_axiomcheck_gen.py from the tip of grh-weil-b569.
-/

#print axioms SIDEExplicitFormula.PageConverses.rh_imp_register4_positivity_liCoeff
#print axioms SIDEExplicitFormula.PageConverses.register4_positivity_liCoeff_iff_rh
#print axioms SIDEExplicitFormula.PageConverses.rh_imp_taylorCoeff_nonneg
#print axioms SIDEExplicitFormula.PageConverses.taylorCoeff_nonneg_iff_rh

#print axioms SIDEExplicitFormula.LiWeil.rh_imp_li_nonneg
#print axioms SIDEExplicitFormula.ResidueDischarge.register4_positivity_liCoeff_imp_rh
#print axioms SIDEExplicitFormula.LiCriterionBridge.li_coeff_eq_taylorCoeff
#print axioms LiCriterion.positivity_implies_RH
#print axioms LiCriterion.rh_equiv_mathlib

#check @SIDEExplicitFormula.PageConverses.rh_imp_register4_positivity_liCoeff
#check @SIDEExplicitFormula.PageConverses.register4_positivity_liCoeff_iff_rh
#check @SIDEExplicitFormula.PageConverses.rh_imp_taylorCoeff_nonneg
#check @SIDEExplicitFormula.PageConverses.taylorCoeff_nonneg_iff_rh

