import SIDEExplicitFormula.Chi.GammaWide
import SIDEExplicitFormula.Chi.VerticalLine
import SIDEExplicitFormula.Chi.Contour

/-!
# Axiom audit -- GRH-Weil act five: the wider-strip bound, the odd-chi step, the prime side and the Gamma side for chi, the rectangle identity (act b570, ruling (R180)(5))

Run `lake env lean AxiomCheckChiAct5.lean` (once the modules are built) to reproduce the `#print axioms` output for every
declaration of the files below and for the terminals they consume by name, the `#check` of the named statements, and
the `#print` of each definition (the salt-check). Each is expected to reduce to the standard base (`propext`,
`Classical.choice`, `Quot.sound`) or less, with no `sorryAx`. The compiler`s output is the verdict, not this comment.
GENERATED by relay tools/b570_axiomcheck_gen.py from the tip of grh-weil-b570.
-/

#print axioms SIDEExplicitFormula.GRHWeil.digamma_growth_strip_wide
#print axioms SIDEExplicitFormula.GRHWeil.norm_logDeriv_Gammaℝ_le_wide
#print axioms SIDEExplicitFormula.GRHWeil.logDeriv_comp_add_one
#print axioms SIDEExplicitFormula.GRHWeil.norm_logDeriv_gammaFactor_le
#print axioms SIDEExplicitFormula.GRHWeil.neg_logDeriv_LFunction_eq
#print axioms SIDEExplicitFormula.GRHWeil.integrand_eq_tsum_chi
#print axioms SIDEExplicitFormula.GRHWeil.per_n_line_integral_chi
#print axioms SIDEExplicitFormula.GRHWeil.line_integral_swap_chi
#print axioms SIDEExplicitFormula.GRHWeil.prime_side_line_chi
#print axioms SIDEExplicitFormula.GRHWeil.analyticAt_gammaFactor
#print axioms SIDEExplicitFormula.GRHWeil.gamma_line_shift_chi
#print axioms SIDEExplicitFormula.GRHWeil.rectangle_identity_chi

#print axioms DirichletCharacter.LSeries_twist_vonMangoldt_eq
#print axioms DirichletCharacter.LSeriesSummable_twist_vonMangoldt
#print axioms Zeta23.WeilEF.norm_logDeriv_Gammaℝ_le
#print axioms Zeta23.WeilEF.tilted_inversion
#print axioms Zeta23.Analytic.rectangleIntegral'_mul_logDeriv
#print axioms Zeta23.StirlingVert.digamma_stirling
#print axioms SIDEExplicitFormula.GRHWeil.completedLFunction_eq_zero_iff

#check @SIDEExplicitFormula.GRHWeil.digamma_growth_strip_wide
#check @SIDEExplicitFormula.GRHWeil.norm_logDeriv_Gammaℝ_le_wide
#check @SIDEExplicitFormula.GRHWeil.logDeriv_comp_add_one
#check @SIDEExplicitFormula.GRHWeil.norm_logDeriv_gammaFactor_le
#check @SIDEExplicitFormula.GRHWeil.neg_logDeriv_LFunction_eq
#check @SIDEExplicitFormula.GRHWeil.integrand_eq_tsum_chi
#check @SIDEExplicitFormula.GRHWeil.per_n_line_integral_chi
#check @SIDEExplicitFormula.GRHWeil.line_integral_swap_chi
#check @SIDEExplicitFormula.GRHWeil.prime_side_line_chi
#check @SIDEExplicitFormula.GRHWeil.analyticAt_gammaFactor
#check @SIDEExplicitFormula.GRHWeil.gamma_line_shift_chi
#check @SIDEExplicitFormula.GRHWeil.rectangle_identity_chi

