import SIDEExplicitFormula.Chi.FullLine
import SIDEExplicitFormula.Chi.Horizontal
import SIDEExplicitFormula.Chi.ZeroSumLimit
import SIDEExplicitFormula.Chi.FullLineAssembly
import SIDEExplicitFormula.Chi.Main

/-!
# Axiom audit -- GRH-Weil act six: FullLine restated at chi^-1 with the conductor, the fold, Horizontal, ZeroSumLimit, the assembly, EF_lit_chi (act b571, ruling (R181)(4))

Run `lake env lean AxiomCheckChiAct6.lean` (once the modules are built) to reproduce the `#print axioms` output for every
declaration of the files below and for the terminals they consume by name, the `#check` of the named statements, and
the `#print` of each definition (the salt-check). Each is expected to reduce to the standard base (`propext`,
`Classical.choice`, `Quot.sound`) or less, with no `sorryAx`. The compiler`s output is the verdict, not this comment.
GENERATED by relay tools/b571_axiomcheck_gen.py from the tip of grh-weil-b571.
-/

#print axioms SIDEExplicitFormula.GRHWeil.logDeriv_completedLFunction_line
#print axioms SIDEExplicitFormula.GRHWeil.norm_logDeriv_LFunction_le_of_one_lt_re
#print axioms SIDEExplicitFormula.GRHWeil.continuous_logDeriv_completedLFunction_line
#print axioms SIDEExplicitFormula.GRHWeil.integrable_mul_of_decay_log
#print axioms SIDEExplicitFormula.GRHWeil.norm_logDeriv_completedLFunction_line_le
#print axioms SIDEExplicitFormula.GRHWeil.completedLFunction_ne_zero_on_horizontals_chi
#print axioms SIDEExplicitFormula.GRHWeil.FlineCond_chi
#print axioms SIDEExplicitFormula.GRHWeil.Fline_chi
#print axioms SIDEExplicitFormula.GRHWeil.integrable_Fline_chi
#print axioms SIDEExplicitFormula.GRHWeil.verticals_eq_chi
#print axioms SIDEExplicitFormula.GRHWeil.tendsto_interval_Fline_chi
#print axioms SIDEExplicitFormula.GRHWeil.logDeriv_LFunction_inv_conj
#print axioms SIDEExplicitFormula.GRHWeil.norm_logDeriv_completed_le_of_good
#print axioms SIDEExplicitFormula.GRHWeil.horizontal_vanish_chi
#print axioms SIDEExplicitFormula.GRHWeil.zero_sum_limit_chi
#print axioms SIDEExplicitFormula.GRHWeil.full_line_identity_chi
#print axioms SIDEExplicitFormula.GRHWeil.even_inv_iff
#print axioms SIDEExplicitFormula.GRHWeil.gammaFactor_inv
#print axioms SIDEExplicitFormula.GRHWeil.inv_apply_natCast
#print axioms SIDEExplicitFormula.GRHWeil.mem_integerComplement_quarter
#print axioms SIDEExplicitFormula.GRHWeil.logDeriv_Gammaℝ_bracket
#print axioms SIDEExplicitFormula.GRHWeil.gammaFactor_bracket
#print axioms SIDEExplicitFormula.GRHWeil.continuous_logDeriv_LFunction_line
#print axioms SIDEExplicitFormula.GRHWeil.continuous_logDeriv_gammaFactor_comp
#print axioms SIDEExplicitFormula.GRHWeil.paperFT_eq_Hfn_half
#print axioms SIDEExplicitFormula.GRHWeil.prime_line_eval
#print axioms SIDEExplicitFormula.GRHWeil.conductor_line_shift
#print axioms SIDEExplicitFormula.GRHWeil.summable_mul_log_of_bounded_support
#print axioms SIDEExplicitFormula.GRHWeil.EF_lit_chi_holds

#print axioms SIDEExplicitFormula.GRHWeil.logDeriv_completedLFunction_one_sub
#print axioms SIDEExplicitFormula.GRHWeil.LFunction_inv_conj
#print axioms SIDEExplicitFormula.GRHWeil.rectangle_identity_chi
#print axioms SIDEExplicitFormula.GRHWeil.good_heights_chi
#print axioms SIDEExplicitFormula.GRHWeil.EF_zero_sum_summable_chi
#print axioms SIDEExplicitFormula.GRHWeil.prime_side_line_chi
#print axioms SIDEExplicitFormula.GRHWeil.gamma_line_shift_chi
#print axioms SIDEExplicitFormula.GRHWeil.norm_logDeriv_gammaFactor_le
#print axioms Zeta23.WeilEF.vertical_line_shift
#print axioms Zeta23.WeilEF.Hfn_mirror
#print axioms Zeta23.WeilEF.logDeriv_Gammaℝ
#print axioms Zeta23.WeilEF.digamma_conj
#print axioms Zeta23.WeilEF.norm_Hfn_le

#check @SIDEExplicitFormula.GRHWeil.logDeriv_completedLFunction_line
#check @SIDEExplicitFormula.GRHWeil.norm_logDeriv_LFunction_le_of_one_lt_re
#check @SIDEExplicitFormula.GRHWeil.continuous_logDeriv_completedLFunction_line
#check @SIDEExplicitFormula.GRHWeil.integrable_mul_of_decay_log
#check @SIDEExplicitFormula.GRHWeil.norm_logDeriv_completedLFunction_line_le
#check @SIDEExplicitFormula.GRHWeil.completedLFunction_ne_zero_on_horizontals_chi
#check @SIDEExplicitFormula.GRHWeil.integrable_Fline_chi
#check @SIDEExplicitFormula.GRHWeil.verticals_eq_chi
#check @SIDEExplicitFormula.GRHWeil.tendsto_interval_Fline_chi
#check @SIDEExplicitFormula.GRHWeil.logDeriv_LFunction_inv_conj
#check @SIDEExplicitFormula.GRHWeil.norm_logDeriv_completed_le_of_good
#check @SIDEExplicitFormula.GRHWeil.horizontal_vanish_chi
#check @SIDEExplicitFormula.GRHWeil.zero_sum_limit_chi
#check @SIDEExplicitFormula.GRHWeil.full_line_identity_chi
#check @SIDEExplicitFormula.GRHWeil.even_inv_iff
#check @SIDEExplicitFormula.GRHWeil.gammaFactor_inv
#check @SIDEExplicitFormula.GRHWeil.inv_apply_natCast
#check @SIDEExplicitFormula.GRHWeil.mem_integerComplement_quarter
#check @SIDEExplicitFormula.GRHWeil.logDeriv_Gammaℝ_bracket
#check @SIDEExplicitFormula.GRHWeil.gammaFactor_bracket
#check @SIDEExplicitFormula.GRHWeil.continuous_logDeriv_LFunction_line
#check @SIDEExplicitFormula.GRHWeil.continuous_logDeriv_gammaFactor_comp
#check @SIDEExplicitFormula.GRHWeil.paperFT_eq_Hfn_half
#check @SIDEExplicitFormula.GRHWeil.prime_line_eval
#check @SIDEExplicitFormula.GRHWeil.conductor_line_shift
#check @SIDEExplicitFormula.GRHWeil.summable_mul_log_of_bounded_support
#check @SIDEExplicitFormula.GRHWeil.EF_lit_chi_holds

#print SIDEExplicitFormula.GRHWeil.FlineCond_chi
#print SIDEExplicitFormula.GRHWeil.Fline_chi
