import SIDEExplicitFormula.Chi.CriterionForward
import SIDEExplicitFormula.Chi.CriterionConverse

/-!
# Axiom audit -- GRH-Weil act seven: the criterion at the chi-instance, h2_sign_chi iff GRH_chi (act b572, ruling (R182)(4))

Run `lake env lean AxiomCheckChiAct7.lean` (once the modules are built) to reproduce the `#print axioms` output for every
declaration of the files below and for the terminals they consume by name, the `#check` of the named statements, and
the `#print` of each definition (the salt-check). Each is expected to reduce to the standard base (`propext`,
`Classical.choice`, `Quot.sound`) or less, with no `sorryAx`. The compiler`s output is the verdict, not this comment.
GENERATED by relay tools/b572_axiomcheck_gen.py from the tip of grh-weil-b572.
-/

#print axioms SIDEExplicitFormula.GRHWeil.zeroSide_chi
#print axioms SIDEExplicitFormula.GRHWeil.zeroSide_chi_eq
#print axioms SIDEExplicitFormula.GRHWeil.rh_strip_chi
#print axioms SIDEExplicitFormula.GRHWeil.rh_strip_chi_iff_grh_chi
#print axioms SIDEExplicitFormula.GRHWeil.rh_strip_chi_imp_h2_sign_chi
#print axioms SIDEExplicitFormula.GRHWeil.grh_chi_imp_h2_sign_chi
#print axioms SIDEExplicitFormula.GRHWeil.dominant_summable_chi
#print axioms SIDEExplicitFormula.GRHWeil.fR_chi
#print axioms SIDEExplicitFormula.GRHWeil.fR_norm_le_chi
#print axioms SIDEExplicitFormula.GRHWeil.fR_bound_chi
#print axioms SIDEExplicitFormula.GRHWeil.rest_tendsto_zero_chi
#print axioms SIDEExplicitFormula.GRHWeil.sT_chi
#print axioms SIDEExplicitFormula.GRHWeil.mem_sT_chi
#print axioms SIDEExplicitFormula.GRHWeil.zeroSide_eventually_neg_chi
#print axioms SIDEExplicitFormula.GRHWeil.h2_sign_chi_imp_rh_strip_chi
#print axioms SIDEExplicitFormula.GRHWeil.h2_sign_chi_imp_grh_chi
#print axioms SIDEExplicitFormula.GRHWeil.h2_sign_chi_iff_grh_chi

#print axioms SIDEExplicitFormula.GRHWeil.EF_lit_chi_holds
#print axioms SIDEExplicitFormula.GRHWeil.chiZeroConfig_local_count
#print axioms SIDEExplicitFormula.B321.weighted_summable
#print axioms SIDEExplicitFormula.B321.plateau_dominant
#print axioms SIDEExplicitFormula.B321.tie_term_neg
#print axioms SIDEExplicitFormula.B321.coeffs_exist
#print axioms SIDEExplicitFormula.B321.kWindow_classK
#print axioms SIDEExplicitFormula.B321.zero_weight
#print axioms SIDEExplicitFormula.B321.h2_sign_iff_rh

#check @SIDEExplicitFormula.GRHWeil.zeroSide_chi_eq
#check @SIDEExplicitFormula.GRHWeil.rh_strip_chi_iff_grh_chi
#check @SIDEExplicitFormula.GRHWeil.rh_strip_chi_imp_h2_sign_chi
#check @SIDEExplicitFormula.GRHWeil.grh_chi_imp_h2_sign_chi
#check @SIDEExplicitFormula.GRHWeil.dominant_summable_chi
#check @SIDEExplicitFormula.GRHWeil.fR_norm_le_chi
#check @SIDEExplicitFormula.GRHWeil.fR_bound_chi
#check @SIDEExplicitFormula.GRHWeil.rest_tendsto_zero_chi
#check @SIDEExplicitFormula.GRHWeil.mem_sT_chi
#check @SIDEExplicitFormula.GRHWeil.zeroSide_eventually_neg_chi
#check @SIDEExplicitFormula.GRHWeil.h2_sign_chi_imp_rh_strip_chi
#check @SIDEExplicitFormula.GRHWeil.h2_sign_chi_imp_grh_chi
#check @SIDEExplicitFormula.GRHWeil.h2_sign_chi_iff_grh_chi

#print SIDEExplicitFormula.GRHWeil.zeroSide_chi
#print SIDEExplicitFormula.GRHWeil.rh_strip_chi
#print SIDEExplicitFormula.GRHWeil.fR_chi
#print SIDEExplicitFormula.GRHWeil.sT_chi
