import SIDEExplicitFormula.Schema.Config
import SIDEExplicitFormula.Schema.Converse
import SIDEExplicitFormula.Schema.Instances

/-!
# Axiom audit -- GRH-Weil act eight: the generic schema, zeta and chi as instances (act b573, ruling (R183)(4))

Run `lake env lean AxiomCheckSchemaAct8.lean` (once the modules are built) to reproduce the `#print axioms` output for every
declaration of the files below and for the terminals they consume by name, the `#check` of the named statements, and
the `#print` of each definition (the salt-check). Each is expected to reduce to the standard base (`propext`,
`Classical.choice`, `Quot.sound`) or less, with no `sorryAx`. The compiler`s output is the verdict, not this comment.
GENERATED by relay tools/b573_axiomcheck_gen.py from the tip of grh-weil-b573.
-/

#print axioms SIDEExplicitFormula.Schema.zeroSide_cfg
#print axioms SIDEExplicitFormula.Schema.h2_sign_cfg
#print axioms SIDEExplicitFormula.Schema.online
#print axioms SIDEExplicitFormula.Schema.zeroSide_cfg_eq
#print axioms SIDEExplicitFormula.Schema.online_imp_h2_sign_cfg
#print axioms SIDEExplicitFormula.Schema.dominant_summable_cfg
#print axioms SIDEExplicitFormula.Schema.fR_cfg
#print axioms SIDEExplicitFormula.Schema.fR_norm_le_cfg
#print axioms SIDEExplicitFormula.Schema.fR_bound_cfg
#print axioms SIDEExplicitFormula.Schema.rest_tendsto_zero_cfg
#print axioms SIDEExplicitFormula.Schema.sT_cfg
#print axioms SIDEExplicitFormula.Schema.mem_sT_cfg
#print axioms SIDEExplicitFormula.Schema.zeroSide_eventually_neg_cfg
#print axioms SIDEExplicitFormula.Schema.h2_sign_cfg_imp_online
#print axioms SIDEExplicitFormula.Schema.h2_sign_cfg_iff_online
#print axioms SIDEExplicitFormula.Schema.h2_sign_cfg_iff_target
#print axioms SIDEExplicitFormula.Schema.zetaWeilConfig
#print axioms SIDEExplicitFormula.Schema.h2_sign_cfg_zeta
#print axioms SIDEExplicitFormula.Schema.h2_sign_cfg_zeta_statement
#print axioms SIDEExplicitFormula.Schema.chiWeilConfig
#print axioms SIDEExplicitFormula.Schema.h2_sign_cfg_chi
#print axioms SIDEExplicitFormula.Schema.h2_sign_cfg_chi_statement

#print axioms SIDEExplicitFormula.B321.h2_sign_iff_rh
#print axioms SIDEExplicitFormula.GRHWeil.h2_sign_chi_iff_grh_chi
#print axioms SIDEExplicitFormula.B321.b321_identity
#print axioms SIDEExplicitFormula.GRHWeil.zeroSide_chi_eq
#print axioms SIDEExplicitFormula.B321.weighted_summable
#print axioms SIDEExplicitFormula.B321.plateau_dominant
#print axioms Zeta23.RvM.zetaZeroConfig_local_count
#print axioms SIDEExplicitFormula.GRHWeil.chiZeroConfig_local_count
#print axioms SIDEExplicitFormula.B321.rh_strip_imp_rh_holds

#check @SIDEExplicitFormula.Schema.zeroSide_cfg_eq
#check @SIDEExplicitFormula.Schema.online_imp_h2_sign_cfg
#check @SIDEExplicitFormula.Schema.dominant_summable_cfg
#check @SIDEExplicitFormula.Schema.fR_norm_le_cfg
#check @SIDEExplicitFormula.Schema.fR_bound_cfg
#check @SIDEExplicitFormula.Schema.rest_tendsto_zero_cfg
#check @SIDEExplicitFormula.Schema.mem_sT_cfg
#check @SIDEExplicitFormula.Schema.zeroSide_eventually_neg_cfg
#check @SIDEExplicitFormula.Schema.h2_sign_cfg_imp_online
#check @SIDEExplicitFormula.Schema.h2_sign_cfg_iff_online
#check @SIDEExplicitFormula.Schema.h2_sign_cfg_iff_target
#check @SIDEExplicitFormula.Schema.h2_sign_cfg_zeta
#check @SIDEExplicitFormula.Schema.h2_sign_cfg_zeta_statement
#check @SIDEExplicitFormula.Schema.h2_sign_cfg_chi
#check @SIDEExplicitFormula.Schema.h2_sign_cfg_chi_statement

#print SIDEExplicitFormula.Schema.zeroSide_cfg
#print SIDEExplicitFormula.Schema.h2_sign_cfg
#print SIDEExplicitFormula.Schema.online
#print SIDEExplicitFormula.Schema.fR_cfg
#print SIDEExplicitFormula.Schema.sT_cfg
#print SIDEExplicitFormula.Schema.zetaWeilConfig
#print SIDEExplicitFormula.Schema.chiWeilConfig
