import SIDEExplicitFormula.ResidueDischarge

/-!
# Axiom audit -- the residue chain`s Li-channel premise discharged: (L1)-(L3) (act b567, ruling (R177)(5))

Run `lake env lean AxiomCheckResidue.lean` (once the modules are built) to reproduce the `#print axioms` output for every
declaration of the files below and for the terminals they consume by name, the `#check` of the named statements, and
the `#print` of each definition (the salt-check). Each is expected to reduce to the standard base (`propext`,
`Classical.choice`, `Quot.sound`) or less, with no `sorryAx`. The compiler`s output is the verdict, not this comment.
GENERATED by relay tools/b567_axiomcheck_gen.py from the tip of residue-discharge-b567.
-/

#print axioms SIDEExplicitFormula.ResidueDischarge.Register4_positivity
#print axioms SIDEExplicitFormula.ResidueDischarge.liCoeff_zero
#print axioms SIDEExplicitFormula.ResidueDischarge.register4_positivity_liCoeff_imp_rh

#print axioms SIDEExplicitFormula.LiCriterionBridge.li_nonneg_iff_rh
#print axioms SIDEExplicitFormula.LiWeil.LiCoeff_eq

#check @SIDEExplicitFormula.ResidueDischarge.register4_positivity_liCoeff_imp_rh
#check @SIDEExplicitFormula.ResidueDischarge.liCoeff_zero

#print SIDEExplicitFormula.ResidueDischarge.Register4_positivity
