import SIDEExplicitFormula.Chi.ZetaBoundsStrip
import SIDEExplicitFormula.Chi.Statement

/-!
# Axiom audit -- GRH-Weil act three: the representation of L(s, χ) on the strip, ZetaBounds` analogue, EF_lit_chi stated (act b567, ruling (R177)(6))

Run `lake env lean AxiomCheckChiStrip.lean` (once the modules are built) to reproduce the `#print axioms` output for every
declaration of the files below and for the terminals they consume by name, the `#check` of the named statements, and
the `#print` of each definition (the salt-check). Each is expected to reduce to the standard base (`propext`,
`Classical.choice`, `Quot.sound`) or less, with no `sorryAx`. The compiler`s output is the verdict, not this comment.
GENERATED by relay tools/b567_axiomcheck_gen.py from the tip of grh-weil-b567.
-/

#print axioms SIDEExplicitFormula.GRHWeil.charPartialSum_eq_zero_of_lt_one
#print axioms SIDEExplicitFormula.GRHWeil.measurable_charPartialSum
#print axioms SIDEExplicitFormula.GRHWeil.locallyIntegrableOn_charPartialSum
#print axioms SIDEExplicitFormula.GRHWeil.charPartialSum_isBigO
#print axioms SIDEExplicitFormula.GRHWeil.LFunction_eq_mul_integral_of_one_lt_re
#print axioms SIDEExplicitFormula.GRHWeil.integral_Ioi_one_eq_mellin
#print axioms SIDEExplicitFormula.GRHWeil.differentiableAt_mellin_charPartialSum
#print axioms SIDEExplicitFormula.GRHWeil.abelRep
#print axioms SIDEExplicitFormula.GRHWeil.differentiableOn_abelRep
#print axioms SIDEExplicitFormula.GRHWeil.LFunction_eq_mul_integral
#print axioms SIDEExplicitFormula.GRHWeil.tailKernel
#print axioms SIDEExplicitFormula.GRHWeil.integral_Ioi_indicator_eq
#print axioms SIDEExplicitFormula.GRHWeil.integral_Ioi_eq_mellin_tail
#print axioms SIDEExplicitFormula.GRHWeil.integral_Ioi_log_eq_mellin_tail
#print axioms SIDEExplicitFormula.GRHWeil.tailKernel_memLp
#print axioms SIDEExplicitFormula.GRHWeil.hasDerivAt_mellin_tail
#print axioms SIDEExplicitFormula.GRHWeil.LFunction0'
#print axioms SIDEExplicitFormula.GRHWeil.hasDerivAt_LFunction0
#print axioms SIDEExplicitFormula.GRHWeil.sum_Icc_zero_char
#print axioms SIDEExplicitFormula.GRHWeil.sum_eq_abel
#print axioms SIDEExplicitFormula.GRHWeil.integrableOn_Ioi_charPartialSum_cpow
#print axioms SIDEExplicitFormula.GRHWeil.LFunction0_eq_LFunction
#print axioms SIDEExplicitFormula.GRHWeil.deriv_LFunction0_eq
#print axioms SIDEExplicitFormula.GRHWeil.deriv_LFunction_eq
#print axioms SIDEExplicitFormula.GRHWeil.norm_integral_tail_le
#print axioms SIDEExplicitFormula.GRHWeil.literatureRHS_chi
#print axioms SIDEExplicitFormula.GRHWeil.EF_lit_chi
#print axioms SIDEExplicitFormula.GRHWeil.gammaBracket_chi_of_even
#print axioms SIDEExplicitFormula.GRHWeil.gammaBracket_chi_of_not_even

#print axioms DirichletCharacter.LFunction_eq_LSeries
#print axioms LSeries_eq_mul_integral
#print axioms mellin_differentiableAt_of_isBigO_rpow
#print axioms mellin_hasDerivAt_of_isBigO_rpow
#print axioms AnalyticOnNhd.eqOn_of_preconnected_of_eventuallyEq
#print axioms sum_mul_eq_sub_sub_integral_mul'
#print axioms SIDEExplicitFormula.GRHWeil.norm_charPartialSum_le

#check @SIDEExplicitFormula.GRHWeil.charPartialSum_eq_zero_of_lt_one
#check @SIDEExplicitFormula.GRHWeil.measurable_charPartialSum
#check @SIDEExplicitFormula.GRHWeil.locallyIntegrableOn_charPartialSum
#check @SIDEExplicitFormula.GRHWeil.charPartialSum_isBigO
#check @SIDEExplicitFormula.GRHWeil.LFunction_eq_mul_integral_of_one_lt_re
#check @SIDEExplicitFormula.GRHWeil.integral_Ioi_one_eq_mellin
#check @SIDEExplicitFormula.GRHWeil.differentiableAt_mellin_charPartialSum
#check @SIDEExplicitFormula.GRHWeil.differentiableOn_abelRep
#check @SIDEExplicitFormula.GRHWeil.LFunction_eq_mul_integral
#check @SIDEExplicitFormula.GRHWeil.integral_Ioi_indicator_eq
#check @SIDEExplicitFormula.GRHWeil.integral_Ioi_eq_mellin_tail
#check @SIDEExplicitFormula.GRHWeil.integral_Ioi_log_eq_mellin_tail
#check @SIDEExplicitFormula.GRHWeil.tailKernel_memLp
#check @SIDEExplicitFormula.GRHWeil.hasDerivAt_mellin_tail
#check @SIDEExplicitFormula.GRHWeil.hasDerivAt_LFunction0
#check @SIDEExplicitFormula.GRHWeil.sum_Icc_zero_char
#check @SIDEExplicitFormula.GRHWeil.sum_eq_abel
#check @SIDEExplicitFormula.GRHWeil.integrableOn_Ioi_charPartialSum_cpow
#check @SIDEExplicitFormula.GRHWeil.LFunction0_eq_LFunction
#check @SIDEExplicitFormula.GRHWeil.deriv_LFunction0_eq
#check @SIDEExplicitFormula.GRHWeil.deriv_LFunction_eq
#check @SIDEExplicitFormula.GRHWeil.norm_integral_tail_le
#check @SIDEExplicitFormula.GRHWeil.gammaBracket_chi_of_even
#check @SIDEExplicitFormula.GRHWeil.gammaBracket_chi_of_not_even

#print SIDEExplicitFormula.GRHWeil.abelRep
#print SIDEExplicitFormula.GRHWeil.tailKernel
#print SIDEExplicitFormula.GRHWeil.LFunction0'
#print SIDEExplicitFormula.GRHWeil.literatureRHS_chi
#print SIDEExplicitFormula.GRHWeil.EF_lit_chi
