import SIDEExplicitFormula.Chi.Generic
import SIDEExplicitFormula.Chi.ZetaBounds

/-!
# Axiom audit -- GRH-Weil act two: the χ-instance, the generic modules consumed, the frontier`s ZetaBounds analogues
(act b564, ruling (R174)(5))

Run `lake env lean AxiomCheckChi.lean` (once the modules are built) to reproduce the `#print axioms` output for every
declaration of `SIDEExplicitFormula/Chi/*.lean`, and the `#print` of each definition (the salt-check). Each is expected to
reduce to the standard base (`propext`, `Classical.choice`, `Quot.sound`) or less, with no `sorryAx`. The compiler`s output
is the verdict, not this comment. GENERATED by relay tools/b564_axiomcheck_gen.py from the branch tip`s files.
-/

#print axioms SIDEExplicitFormula.GRHWeil.IsNontrivialZeroChi
#print axioms SIDEExplicitFormula.GRHWeil.zeroMultChi
#print axioms SIDEExplicitFormula.GRHWeil.LFunction_analyticOnNhd
#print axioms SIDEExplicitFormula.GRHWeil.LFunction_two_ne_zero
#print axioms SIDEExplicitFormula.GRHWeil.analyticOrderAt_LFunction_ne_top
#print axioms SIDEExplicitFormula.GRHWeil.one_le_zeroMultChi
#print axioms SIDEExplicitFormula.GRHWeil.LFunction_zeros_locallyFinite
#print axioms SIDEExplicitFormula.GRHWeil.finite_window_chi
#print axioms SIDEExplicitFormula.GRHWeil.gammaFactor_inv_differentiable
#print axioms SIDEExplicitFormula.GRHWeil.analyticOrderAt_LFunction_eq_completed
#print axioms SIDEExplicitFormula.GRHWeil.analyticOrderAt_completed_le_one_sub
#print axioms SIDEExplicitFormula.GRHWeil.analyticOrderAt_completed_one_sub
#print axioms SIDEExplicitFormula.GRHWeil.reflect_eq_conj_one_sub
#print axioms SIDEExplicitFormula.GRHWeil.chi_reflect_zero
#print axioms SIDEExplicitFormula.GRHWeil.chi_mult_reflect
#print axioms SIDEExplicitFormula.GRHWeil.chiZeroConfig
#print axioms SIDEExplicitFormula.GRHWeil.chiZeroConfig_carrier
#print axioms SIDEExplicitFormula.GRHWeil.chiZeroConfig_mult
#print axioms SIDEExplicitFormula.GRHWeil.chiZeroConfig_conj_mem
#print axioms SIDEExplicitFormula.GRHWeil.chiZeroConfig_mult_conj
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Assembly_BlockInputs
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Assembly_BlockInputs_hat
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Assembly_BlockInputs_tilde
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Assembly_NII
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Assembly_TailInputs
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Assembly_TailInputs_hat
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Assembly_TailInputs_theta_nonneg
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Assembly_TailInputs_tilde
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_Az
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_Ez
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_Gsummand
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_Gz
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_N
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_N0
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_N0s
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_N0star
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_NIprime
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_Nd
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_NonIprime
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_Ns
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_S1
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_S2
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_W
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_Wsummand
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_ZIprime
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_ctorIdx
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_offLine
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_p
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_s1
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_s2
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_simple
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_window
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_N0star_le_Nd
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_Nd_le_N
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_finsum_mult_mono
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_ncard_le_finsum_mult
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_ncard_mono
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_trivial_chain
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_window_finite
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_window_subset_carrier
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_EF_EF_lit
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_EF_EF_paper
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_EF_prop_EF_of_lit
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_EF_explicitFormulaPaper_of_lit
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ExplicitFormulaPaper
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_PaperInputs
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_PaperInputs_EF
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_PaperInputs_Gamma
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_PaperInputs_MV
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_PaperInputs_RvM
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_PaperInputs_cheb
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_RiemannVonMangoldt
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_RiemannVonMangoldt_local_count
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_RiemannVonMangoldt_main
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_N_le_two_mul_half
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_reflect_mem_window
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_Gsummand_eq
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_LocalCount_ofWindowCount
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_NII_le
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_Az_eq_sum
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_A₀_nonneg
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_Ez_isHermitian
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_K
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_K_congr_simp
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_K_nonneg
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_L_pos
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_T_pos
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_hA₀
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_hC₁
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_hL
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_hT
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_hasSum_Ez
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_hat_Ez_isHermitian
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_hdecay
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_hloc
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_not_mem_sA_iff
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_partial_sum_le
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_sA
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_summable_Gsummand
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_summable_tail
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_tailInputs
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_tilde_Ez_isHermitian
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_traceNorm_smul_Ez_le
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_tsum_tail_le
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_eventually_NII_le
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_eventually_tailInputs
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_finite_notTail
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_norm_sq_uvec_le
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_norm_uvec_le
#print axioms SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_prop_tail
#print axioms SIDEExplicitFormula.GRHWeil.analyticAt_LFunction
#print axioms SIDEExplicitFormula.GRHWeil.differentiableAt_deriv_LFunction
#print axioms SIDEExplicitFormula.GRHWeil.LFunction_bddAbove_near_one
#print axioms SIDEExplicitFormula.GRHWeil.continuousAt_neg_logDeriv_LFunction_one
#print axioms SIDEExplicitFormula.GRHWeil.LFunction_logDeriv_bddAbove_near_one
#print axioms SIDEExplicitFormula.GRHWeil.LFunction_logDeriv_isBigO_one
#print axioms SIDEExplicitFormula.GRHWeil.charPartialSum
#print axioms SIDEExplicitFormula.GRHWeil.sum_range_block_char_eq_zero
#print axioms SIDEExplicitFormula.GRHWeil.norm_sum_range_char_le
#print axioms SIDEExplicitFormula.GRHWeil.norm_charPartialSum_le
#print axioms SIDEExplicitFormula.GRHWeil.LFunction0

#print SIDEExplicitFormula.GRHWeil.IsNontrivialZeroChi
#print SIDEExplicitFormula.GRHWeil.zeroMultChi
#print SIDEExplicitFormula.GRHWeil.chiZeroConfig
#print SIDEExplicitFormula.GRHWeil.Generic.chi_Assembly_BlockInputs
#print SIDEExplicitFormula.GRHWeil.Generic.chi_Assembly_NII
#print SIDEExplicitFormula.GRHWeil.Generic.chi_Assembly_TailInputs
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_Az
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_Ez
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_Gsummand
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_Gz
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_N
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_N0
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_N0s
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_N0star
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_NIprime
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_Nd
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_NonIprime
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_Ns
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_S1
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_S2
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_W
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_Wsummand
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_ZIprime
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_ctorIdx
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_offLine
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_p
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_s1
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_s2
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_simple
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ZeroConfig_window
#print SIDEExplicitFormula.GRHWeil.Generic.chi_EF_EF_lit
#print SIDEExplicitFormula.GRHWeil.Generic.chi_EF_EF_paper
#print SIDEExplicitFormula.GRHWeil.Generic.chi_ExplicitFormulaPaper
#print SIDEExplicitFormula.GRHWeil.Generic.chi_PaperInputs
#print SIDEExplicitFormula.GRHWeil.Generic.chi_RiemannVonMangoldt
#print SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp
#print SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_K
#print SIDEExplicitFormula.GRHWeil.Generic.chi_Tail_TailHyp_sA
#print SIDEExplicitFormula.GRHWeil.charPartialSum
#print SIDEExplicitFormula.GRHWeil.LFunction0
