import SIDEExplicitFormula.Chi.ZetaGrowth
import SIDEExplicitFormula.Chi.LocalCount
import SIDEExplicitFormula.Chi.ZeroSummability
import SIDEExplicitFormula.Chi.XiLogDeriv
import SIDEExplicitFormula.Chi.CountByIntegral
import SIDEExplicitFormula.Chi.Landau
import SIDEExplicitFormula.Chi.GoodHeights

/-!
# Axiom audit -- GRH-Weil act four: the chi-analogues of EF_lit`s route from ZetaGrowth to GoodHeights (act b569, ruling (R179)(6))

Run `lake env lean AxiomCheckChiRoute.lean` (once the modules are built) to reproduce the `#print axioms` output for every
declaration of the files below and for the terminals they consume by name, the `#check` of the named statements, and
the `#print` of each definition (the salt-check). Each is expected to reduce to the standard base (`propext`,
`Classical.choice`, `Quot.sound`) or less, with no `sorryAx`. The compiler`s output is the verdict, not this comment.
GENERATED by relay tools/b569_axiomcheck_gen.py from the tip of grh-weil-b569.
-/

#print axioms SIDEExplicitFormula.GRHWeil.analyticOnNhd_LFunction
#print axioms SIDEExplicitFormula.GRHWeil.norm_LFunction_le_of_re_pos
#print axioms SIDEExplicitFormula.GRHWeil.norm_div_re_le
#print axioms SIDEExplicitFormula.GRHWeil.LFunction_linear_growth
#print axioms SIDEExplicitFormula.GRHWeil.LFunction_growth
#print axioms SIDEExplicitFormula.GRHWeil.LFunction_growth_quarter
#print axioms SIDEExplicitFormula.GRHWeil.LFunction_growth_right_at
#print axioms SIDEExplicitFormula.GRHWeil.LFunction_growth_right
#print axioms SIDEExplicitFormula.GRHWeil.norm_LFunction_sub_one_le
#print axioms SIDEExplicitFormula.GRHWeil.pi_sq_div_six_sub_one_lt_one'
#print axioms SIDEExplicitFormula.GRHWeil.one_third_lt_two_sub_pi_sq_div_six'
#print axioms SIDEExplicitFormula.GRHWeil.norm_LFunction_ge_of_two_le_re
#print axioms SIDEExplicitFormula.GRHWeil.LFunction_lower_bound_two
#print axioms SIDEExplicitFormula.GRHWeil.LFunction_ne_zero_of_two_le_re
#print axioms SIDEExplicitFormula.GRHWeil.norm_LFunction_le_of_two_le_re
#print axioms SIDEExplicitFormula.GRHWeil.LFunction_zeros_finite_of_isCompact
#print axioms SIDEExplicitFormula.GRHWeil.gfunChi
#print axioms SIDEExplicitFormula.GRHWeil.comp_affine_analyticAt_chi
#print axioms SIDEExplicitFormula.GRHWeil.gfunChi_analyticAt
#print axioms SIDEExplicitFormula.GRHWeil.analyticOrderNatAt_gfunChi
#print axioms SIDEExplicitFormula.GRHWeil.NhalfChi
#print axioms SIDEExplicitFormula.GRHWeil.half_count_large_chi
#print axioms SIDEExplicitFormula.GRHWeil.count_small_chi
#print axioms SIDEExplicitFormula.GRHWeil.chiZeroConfig_local_count
#print axioms SIDEExplicitFormula.GRHWeil.chi_zero_sum_inv_sq
#print axioms SIDEExplicitFormula.GRHWeil.EF_zero_sum_summable_chi
#print axioms SIDEExplicitFormula.GRHWeil.differentiableAt_gammaFactor
#print axioms SIDEExplicitFormula.GRHWeil.completedLFunction_eventuallyEq_mul
#print axioms SIDEExplicitFormula.GRHWeil.logDeriv_completedLFunction
#print axioms SIDEExplicitFormula.GRHWeil.completedLFunction_ne_zero_of_one_le_re
#print axioms SIDEExplicitFormula.GRHWeil.rootNumber_ne_zero
#print axioms SIDEExplicitFormula.GRHWeil.logDeriv_completedLFunction_one_sub
#print axioms SIDEExplicitFormula.GRHWeil.completedLFunction_zeros_strip
#print axioms SIDEExplicitFormula.GRHWeil.analyticAt_completedLFunction
#print axioms SIDEExplicitFormula.GRHWeil.completedLFunction_eq_zero_iff_of_re_pos
#print axioms SIDEExplicitFormula.GRHWeil.completedLFunction_ne_zero_of_re_nonpos
#print axioms SIDEExplicitFormula.GRHWeil.completedLFunction_eq_zero_iff
#print axioms SIDEExplicitFormula.GRHWeil.analyticOrderNatAt_completedLFunction
#print axioms SIDEExplicitFormula.GRHWeil.LFunction_logDeriv_partial_fraction
#print axioms SIDEExplicitFormula.GRHWeil.isNontrivialZeroChi_of_mem_closedBall
#print axioms SIDEExplicitFormula.GRHWeil.sum_mult_six_windows_chi
#print axioms SIDEExplicitFormula.GRHWeil.card_le_sum_mult_chi
#print axioms SIDEExplicitFormula.GRHWeil.good_heights_at_chi
#print axioms SIDEExplicitFormula.GRHWeil.good_heights_chi

#print axioms DirichletCharacter.LFunction_eq_LSeries
#print axioms DirichletCharacter.IsPrimitive.completedLFunction_one_sub
#print axioms Zeta23.WeilEF.EF_zero_sum_summable_gen
#print axioms Zeta23.WeilEF.logDeriv_partial_fraction_disk
#print axioms ZerosBound
#print axioms SIDEExplicitFormula.GRHWeil.LFunction_eq_mul_integral
#print axioms SIDEExplicitFormula.GRHWeil.norm_integral_tail_le

#check @SIDEExplicitFormula.GRHWeil.analyticOnNhd_LFunction
#check @SIDEExplicitFormula.GRHWeil.norm_LFunction_le_of_re_pos
#check @SIDEExplicitFormula.GRHWeil.norm_div_re_le
#check @SIDEExplicitFormula.GRHWeil.LFunction_linear_growth
#check @SIDEExplicitFormula.GRHWeil.LFunction_growth
#check @SIDEExplicitFormula.GRHWeil.LFunction_growth_quarter
#check @SIDEExplicitFormula.GRHWeil.LFunction_growth_right_at
#check @SIDEExplicitFormula.GRHWeil.LFunction_growth_right
#check @SIDEExplicitFormula.GRHWeil.norm_LFunction_sub_one_le
#check @SIDEExplicitFormula.GRHWeil.pi_sq_div_six_sub_one_lt_one'
#check @SIDEExplicitFormula.GRHWeil.one_third_lt_two_sub_pi_sq_div_six'
#check @SIDEExplicitFormula.GRHWeil.norm_LFunction_ge_of_two_le_re
#check @SIDEExplicitFormula.GRHWeil.LFunction_lower_bound_two
#check @SIDEExplicitFormula.GRHWeil.LFunction_ne_zero_of_two_le_re
#check @SIDEExplicitFormula.GRHWeil.norm_LFunction_le_of_two_le_re
#check @SIDEExplicitFormula.GRHWeil.LFunction_zeros_finite_of_isCompact
#check @SIDEExplicitFormula.GRHWeil.comp_affine_analyticAt_chi
#check @SIDEExplicitFormula.GRHWeil.gfunChi_analyticAt
#check @SIDEExplicitFormula.GRHWeil.analyticOrderNatAt_gfunChi
#check @SIDEExplicitFormula.GRHWeil.half_count_large_chi
#check @SIDEExplicitFormula.GRHWeil.count_small_chi
#check @SIDEExplicitFormula.GRHWeil.chiZeroConfig_local_count
#check @SIDEExplicitFormula.GRHWeil.chi_zero_sum_inv_sq
#check @SIDEExplicitFormula.GRHWeil.EF_zero_sum_summable_chi
#check @SIDEExplicitFormula.GRHWeil.differentiableAt_gammaFactor
#check @SIDEExplicitFormula.GRHWeil.completedLFunction_eventuallyEq_mul
#check @SIDEExplicitFormula.GRHWeil.logDeriv_completedLFunction
#check @SIDEExplicitFormula.GRHWeil.completedLFunction_ne_zero_of_one_le_re
#check @SIDEExplicitFormula.GRHWeil.rootNumber_ne_zero
#check @SIDEExplicitFormula.GRHWeil.logDeriv_completedLFunction_one_sub
#check @SIDEExplicitFormula.GRHWeil.completedLFunction_zeros_strip
#check @SIDEExplicitFormula.GRHWeil.analyticAt_completedLFunction
#check @SIDEExplicitFormula.GRHWeil.completedLFunction_eq_zero_iff_of_re_pos
#check @SIDEExplicitFormula.GRHWeil.completedLFunction_ne_zero_of_re_nonpos
#check @SIDEExplicitFormula.GRHWeil.completedLFunction_eq_zero_iff
#check @SIDEExplicitFormula.GRHWeil.analyticOrderNatAt_completedLFunction
#check @SIDEExplicitFormula.GRHWeil.LFunction_logDeriv_partial_fraction
#check @SIDEExplicitFormula.GRHWeil.isNontrivialZeroChi_of_mem_closedBall
#check @SIDEExplicitFormula.GRHWeil.sum_mult_six_windows_chi
#check @SIDEExplicitFormula.GRHWeil.card_le_sum_mult_chi
#check @SIDEExplicitFormula.GRHWeil.good_heights_at_chi
#check @SIDEExplicitFormula.GRHWeil.good_heights_chi

#print SIDEExplicitFormula.GRHWeil.gfunChi
#print SIDEExplicitFormula.GRHWeil.NhalfChi
