name = "SIDEExplicitFormula"
defaultTargets = ["SIDEExplicitFormula"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "de5ce8a9a66a4aa68a9bdbb35b63a06d34d9ca11"

[[lean_lib]]
name = "SIDEExplicitFormula"
globs = ["Zeta23.+", "SIDEExplicitFormula.+"]
