/-
SIDE-explicit-formula -- SIDEExplicitFormula/Chi/Generic.lean
THIS PROGRAMME'S WORK (act b564, ruling (R174)(5)(b); W-ORD-GRH-WEIL, act two) -- NOT VENDORED.
SPIRAL_MAP section 7 rule 9 applies here in full: `theorem`, never `lemma`.

THE GENERIC MODULES CONSUMED BY THE χ-INSTANCE. Every Zeta23 module the DAG bank classes GENERIC is imported below,
unedited, and every top-level declaration of those modules whose type has a binder of type `Zeta23.ZeroConfig`
(found by a `run_cmd` scan over the environment, relay data/b564_generic_leanscan.txt) is applied to `chiZeroConfig`.
Each `chi_<name>` has the type of that application (`type_of%`) and the application as its body: nothing is
re-proved, nothing copied. GENERATED by relay tools/b564_generic_gen.py; not edited by hand.

Nothing here proves GRH, RH, or any statement about the zeros of `LFunction χ` beyond these instantiations.
-/
import SIDEExplicitFormula.Chi.ZeroConfig
import Zeta23.Analytic.RectangleLogDeriv
import Zeta23.Analytic.Stirling
import Zeta23.Assembly.Inputs
import Zeta23.Defs
import Zeta23.Defs.Counting
import Zeta23.ExplicitFormula
import Zeta23.ExplicitFormula.Bridge
import Zeta23.FromPNTPlus.Auxiliary
import Zeta23.FromPNTPlus.EulerMaclaurin
import Zeta23.FromPNTPlus.Fourier
import Zeta23.FromPNTPlus.Mathlib.Analysis.SpecialFunctions.Log.Basic
import Zeta23.FromPNTPlus.Rectangle
import Zeta23.FromPNTPlus.ResidueCalcOnRectangles
import Zeta23.FromPNTPlus.Sobolev
import Zeta23.FromPNTPlus.StrongPNTPrefix
import Zeta23.FromPNTPlus.Tactic.AdditiveCombination
import Zeta23.GammaFacts
import Zeta23.GammaFacts.Mu
import Zeta23.GammaFacts.Series
import Zeta23.GammaFacts.StirlingVert
import Zeta23.Hypotheses
import Zeta23.LinAlg
import Zeta23.LinAlg.HermitianPosPart
import Zeta23.LinAlg.Inertia
import Zeta23.LinAlg.PosIndex
import Zeta23.LinAlg.RankTrace
import Zeta23.LinAlg.Sylvester
import Zeta23.LinAlg.VonNeumann
import Zeta23.LinAlg.Weyl
import Zeta23.Poisson.PaperFT
import Zeta23.Prelude.InstancePriorities
import Zeta23.RvM.Halving
import Zeta23.Tail
import Zeta23.Tail.Basic
import Zeta23.Tail.Count
import Zeta23.Tail.Grid
import Zeta23.Tail.RankOne
import Zeta23.WeilEF.GammaRBracket

noncomputable section

namespace SIDEExplicitFormula
namespace GRHWeil
namespace Generic

open DirichletCharacter

variable {N : ℕ} [NeZero N]

/-- `Zeta23.Assembly.BlockInputs` (Zeta23.Assembly.Inputs) at the χ-instance. -/
def chi_Assembly_BlockInputs (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Assembly.BlockInputs (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Assembly.BlockInputs (chiZeroConfig χ hχ h1)

/-- `Zeta23.Assembly.BlockInputs.hat` (Zeta23.Assembly.Inputs) at the χ-instance. -/
theorem chi_Assembly_BlockInputs_hat (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Assembly.BlockInputs.hat (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Assembly.BlockInputs.hat (chiZeroConfig χ hχ h1)

/-- `Zeta23.Assembly.BlockInputs.tilde` (Zeta23.Assembly.Inputs) at the χ-instance. -/
theorem chi_Assembly_BlockInputs_tilde (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Assembly.BlockInputs.tilde (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Assembly.BlockInputs.tilde (chiZeroConfig χ hχ h1)

/-- `Zeta23.Assembly.NII` (Zeta23.Assembly.Inputs) at the χ-instance. -/
def chi_Assembly_NII (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Assembly.NII (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Assembly.NII (chiZeroConfig χ hχ h1)

/-- `Zeta23.Assembly.TailInputs` (Zeta23.Assembly.Inputs) at the χ-instance. -/
def chi_Assembly_TailInputs (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Assembly.TailInputs (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Assembly.TailInputs (chiZeroConfig χ hχ h1)

/-- `Zeta23.Assembly.TailInputs.hat` (Zeta23.Assembly.Inputs) at the χ-instance. -/
theorem chi_Assembly_TailInputs_hat (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Assembly.TailInputs.hat (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Assembly.TailInputs.hat (chiZeroConfig χ hχ h1)

/-- `Zeta23.Assembly.TailInputs.theta_nonneg` (Zeta23.Assembly.Inputs) at the χ-instance. -/
theorem chi_Assembly_TailInputs_theta_nonneg (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Assembly.TailInputs.theta_nonneg (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Assembly.TailInputs.theta_nonneg (chiZeroConfig χ hχ h1)

/-- `Zeta23.Assembly.TailInputs.tilde` (Zeta23.Assembly.Inputs) at the χ-instance. -/
theorem chi_Assembly_TailInputs_tilde (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Assembly.TailInputs.tilde (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Assembly.TailInputs.tilde (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.Az` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_Az (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.Az (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.Az (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.Ez` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_Ez (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.Ez (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.Ez (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.Gsummand` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_Gsummand (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.Gsummand (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.Gsummand (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.Gz` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_Gz (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.Gz (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.Gz (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.N` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_N (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.N (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.N (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.N0` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_N0 (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.N0 (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.N0 (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.N0s` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_N0s (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.N0s (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.N0s (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.N0star` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_N0star (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.N0star (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.N0star (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.NIprime` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_NIprime (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.NIprime (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.NIprime (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.Nd` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_Nd (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.Nd (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.Nd (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.NonIprime` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_NonIprime (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.NonIprime (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.NonIprime (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.Ns` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_Ns (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.Ns (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.Ns (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.S1` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_S1 (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.S1 (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.S1 (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.S2` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_S2 (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.S2 (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.S2 (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.W` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_W (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.W (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.W (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.Wsummand` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_Wsummand (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.Wsummand (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.Wsummand (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.ZIprime` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_ZIprime (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.ZIprime (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.ZIprime (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.ctorIdx` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_ctorIdx (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.ctorIdx (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.ctorIdx (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.offLine` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_offLine (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.offLine (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.offLine (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.p` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_p (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.p (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.p (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.s1` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_s1 (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.s1 (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.s1 (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.s2` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_s2 (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.s2 (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.s2 (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.simple` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_simple (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.simple (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.simple (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.window` (Zeta23.Defs) at the χ-instance. -/
def chi_ZeroConfig_window (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.window (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.window (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.N0star_le_Nd` (Zeta23.Defs.Counting) at the χ-instance. -/
theorem chi_ZeroConfig_N0star_le_Nd (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.N0star_le_Nd (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.N0star_le_Nd (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.Nd_le_N` (Zeta23.Defs.Counting) at the χ-instance. -/
theorem chi_ZeroConfig_Nd_le_N (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.Nd_le_N (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.Nd_le_N (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.finsum_mult_mono` (Zeta23.Defs.Counting) at the χ-instance. -/
theorem chi_ZeroConfig_finsum_mult_mono (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.finsum_mult_mono (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.finsum_mult_mono (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.ncard_le_finsum_mult` (Zeta23.Defs.Counting) at the χ-instance. -/
theorem chi_ZeroConfig_ncard_le_finsum_mult (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.ncard_le_finsum_mult (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.ncard_le_finsum_mult (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.ncard_mono` (Zeta23.Defs.Counting) at the χ-instance. -/
theorem chi_ZeroConfig_ncard_mono (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.ncard_mono (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.ncard_mono (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.trivial_chain` (Zeta23.Defs.Counting) at the χ-instance. -/
theorem chi_ZeroConfig_trivial_chain (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.trivial_chain (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.trivial_chain (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.window_finite` (Zeta23.Defs.Counting) at the χ-instance. -/
theorem chi_ZeroConfig_window_finite (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.window_finite (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.window_finite (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.window_subset_carrier` (Zeta23.Defs.Counting) at the χ-instance. -/
theorem chi_ZeroConfig_window_subset_carrier (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.window_subset_carrier (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.window_subset_carrier (chiZeroConfig χ hχ h1)

/-- `Zeta23.EF.EF_lit` (Zeta23.ExplicitFormula) at the χ-instance. -/
def chi_EF_EF_lit (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.EF.EF_lit (chiZeroConfig χ hχ h1)) :=
  @Zeta23.EF.EF_lit (chiZeroConfig χ hχ h1)

/-- `Zeta23.EF.EF_paper` (Zeta23.ExplicitFormula) at the χ-instance. -/
def chi_EF_EF_paper (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.EF.EF_paper (chiZeroConfig χ hχ h1)) :=
  @Zeta23.EF.EF_paper (chiZeroConfig χ hχ h1)

/-- `Zeta23.EF.prop_EF_of_lit` (Zeta23.ExplicitFormula) at the χ-instance. -/
theorem chi_EF_prop_EF_of_lit (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.EF.prop_EF_of_lit (chiZeroConfig χ hχ h1)) :=
  @Zeta23.EF.prop_EF_of_lit (chiZeroConfig χ hχ h1)

/-- `Zeta23.EF.explicitFormulaPaper_of_lit` (Zeta23.ExplicitFormula.Bridge) at the χ-instance. -/
theorem chi_EF_explicitFormulaPaper_of_lit (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.EF.explicitFormulaPaper_of_lit (chiZeroConfig χ hχ h1)) :=
  @Zeta23.EF.explicitFormulaPaper_of_lit (chiZeroConfig χ hχ h1)

/-- `Zeta23.ExplicitFormulaPaper` (Zeta23.Hypotheses) at the χ-instance. -/
def chi_ExplicitFormulaPaper (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ExplicitFormulaPaper (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ExplicitFormulaPaper (chiZeroConfig χ hχ h1)

/-- `Zeta23.PaperInputs` (Zeta23.Hypotheses) at the χ-instance. -/
def chi_PaperInputs (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.PaperInputs (chiZeroConfig χ hχ h1)) :=
  @Zeta23.PaperInputs (chiZeroConfig χ hχ h1)

/-- `Zeta23.PaperInputs.EF` (Zeta23.Hypotheses) at the χ-instance. -/
theorem chi_PaperInputs_EF (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.PaperInputs.EF (chiZeroConfig χ hχ h1)) :=
  @Zeta23.PaperInputs.EF (chiZeroConfig χ hχ h1)

/-- `Zeta23.PaperInputs.Gamma` (Zeta23.Hypotheses) at the χ-instance. -/
theorem chi_PaperInputs_Gamma (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.PaperInputs.Gamma (chiZeroConfig χ hχ h1)) :=
  @Zeta23.PaperInputs.Gamma (chiZeroConfig χ hχ h1)

/-- `Zeta23.PaperInputs.MV` (Zeta23.Hypotheses) at the χ-instance. -/
theorem chi_PaperInputs_MV (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.PaperInputs.MV (chiZeroConfig χ hχ h1)) :=
  @Zeta23.PaperInputs.MV (chiZeroConfig χ hχ h1)

/-- `Zeta23.PaperInputs.RvM` (Zeta23.Hypotheses) at the χ-instance. -/
theorem chi_PaperInputs_RvM (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.PaperInputs.RvM (chiZeroConfig χ hχ h1)) :=
  @Zeta23.PaperInputs.RvM (chiZeroConfig χ hχ h1)

/-- `Zeta23.PaperInputs.cheb` (Zeta23.Hypotheses) at the χ-instance. -/
theorem chi_PaperInputs_cheb (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.PaperInputs.cheb (chiZeroConfig χ hχ h1)) :=
  @Zeta23.PaperInputs.cheb (chiZeroConfig χ hχ h1)

/-- `Zeta23.RiemannVonMangoldt` (Zeta23.Hypotheses) at the χ-instance. -/
def chi_RiemannVonMangoldt (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.RiemannVonMangoldt (chiZeroConfig χ hχ h1)) :=
  @Zeta23.RiemannVonMangoldt (chiZeroConfig χ hχ h1)

/-- `Zeta23.RiemannVonMangoldt.local_count` (Zeta23.Hypotheses) at the χ-instance. -/
theorem chi_RiemannVonMangoldt_local_count (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.RiemannVonMangoldt.local_count (chiZeroConfig χ hχ h1)) :=
  @Zeta23.RiemannVonMangoldt.local_count (chiZeroConfig χ hχ h1)

/-- `Zeta23.RiemannVonMangoldt.main` (Zeta23.Hypotheses) at the χ-instance. -/
theorem chi_RiemannVonMangoldt_main (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.RiemannVonMangoldt.main (chiZeroConfig χ hχ h1)) :=
  @Zeta23.RiemannVonMangoldt.main (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.N_le_two_mul_half` (Zeta23.RvM.Halving) at the χ-instance. -/
theorem chi_ZeroConfig_N_le_two_mul_half (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.N_le_two_mul_half (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.N_le_two_mul_half (chiZeroConfig χ hχ h1)

/-- `Zeta23.ZeroConfig.reflect_mem_window` (Zeta23.RvM.Halving) at the χ-instance. -/
theorem chi_ZeroConfig_reflect_mem_window (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.ZeroConfig.reflect_mem_window (chiZeroConfig χ hχ h1)) :=
  @Zeta23.ZeroConfig.reflect_mem_window (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.Gsummand_eq` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_Gsummand_eq (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.Gsummand_eq (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.Gsummand_eq (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.LocalCount.ofWindowCount` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_LocalCount_ofWindowCount (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.LocalCount.ofWindowCount (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.LocalCount.ofWindowCount (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.NII_le` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_NII_le (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.NII_le (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.NII_le (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp` (Zeta23.Tail) at the χ-instance. -/
def chi_Tail_TailHyp (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.Az_eq_sum` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_Az_eq_sum (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.Az_eq_sum (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.Az_eq_sum (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.A₀_nonneg` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_A₀_nonneg (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.A₀_nonneg (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.A₀_nonneg (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.Ez_isHermitian` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_Ez_isHermitian (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% ((fun (x0 : _) (x1 : _) => @Zeta23.Tail.TailHyp.Ez_isHermitian x0 x1 (chiZeroConfig χ hχ h1))) :=
  (fun (x0 : _) (x1 : _) => @Zeta23.Tail.TailHyp.Ez_isHermitian x0 x1 (chiZeroConfig χ hχ h1))

/-- `Zeta23.Tail.TailHyp.K` (Zeta23.Tail) at the χ-instance. -/
def chi_Tail_TailHyp_K (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.K (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.K (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.K.congr_simp` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_K_congr_simp (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.K.congr_simp (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.K.congr_simp (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.K_nonneg` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_K_nonneg (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.K_nonneg (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.K_nonneg (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.L_pos` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_L_pos (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.L_pos (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.L_pos (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.T_pos` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_T_pos (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.T_pos (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.T_pos (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.hA₀` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_hA₀ (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.hA₀ (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.hA₀ (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.hC₁` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_hC₁ (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.hC₁ (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.hC₁ (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.hL` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_hL (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.hL (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.hL (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.hT` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_hT (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.hT (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.hT (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.hasSum_Ez` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_hasSum_Ez (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.hasSum_Ez (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.hasSum_Ez (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.hat_Ez_isHermitian` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_hat_Ez_isHermitian (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% ((fun (x0 : _) (x1 : _) => @Zeta23.Tail.TailHyp.hat_Ez_isHermitian x0 x1 (chiZeroConfig χ hχ h1))) :=
  (fun (x0 : _) (x1 : _) => @Zeta23.Tail.TailHyp.hat_Ez_isHermitian x0 x1 (chiZeroConfig χ hχ h1))

/-- `Zeta23.Tail.TailHyp.hdecay` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_hdecay (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.hdecay (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.hdecay (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.hloc` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_hloc (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.hloc (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.hloc (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.not_mem_sA_iff` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_not_mem_sA_iff (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.not_mem_sA_iff (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.not_mem_sA_iff (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.partial_sum_le` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_partial_sum_le (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.partial_sum_le (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.partial_sum_le (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.sA` (Zeta23.Tail) at the χ-instance. -/
def chi_Tail_TailHyp_sA (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.sA (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.sA (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.summable_Gsummand` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_summable_Gsummand (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.summable_Gsummand (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.summable_Gsummand (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.summable_tail` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_summable_tail (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.summable_tail (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.summable_tail (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.tailInputs` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_tailInputs (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.tailInputs (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.tailInputs (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.tilde_Ez_isHermitian` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_tilde_Ez_isHermitian (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% ((fun (x0 : _) (x1 : _) => @Zeta23.Tail.TailHyp.tilde_Ez_isHermitian x0 x1 (chiZeroConfig χ hχ h1))) :=
  (fun (x0 : _) (x1 : _) => @Zeta23.Tail.TailHyp.tilde_Ez_isHermitian x0 x1 (chiZeroConfig χ hχ h1))

/-- `Zeta23.Tail.TailHyp.traceNorm_smul_Ez_le` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_traceNorm_smul_Ez_le (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.traceNorm_smul_Ez_le (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.traceNorm_smul_Ez_le (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.TailHyp.tsum_tail_le` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_TailHyp_tsum_tail_le (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.TailHyp.tsum_tail_le (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.TailHyp.tsum_tail_le (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.eventually_NII_le` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_eventually_NII_le (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.eventually_NII_le (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.eventually_NII_le (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.eventually_tailInputs` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_eventually_tailInputs (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.eventually_tailInputs (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.eventually_tailInputs (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.finite_notTail` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_finite_notTail (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.finite_notTail (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.finite_notTail (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.norm_sq_uvec_le` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_norm_sq_uvec_le (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.norm_sq_uvec_le (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.norm_sq_uvec_le (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.norm_uvec_le` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_norm_uvec_le (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.norm_uvec_le (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.norm_uvec_le (chiZeroConfig χ hχ h1)

/-- `Zeta23.Tail.prop_tail` (Zeta23.Tail) at the χ-instance. -/
theorem chi_Tail_prop_tail (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :
    type_of% (@Zeta23.Tail.prop_tail (chiZeroConfig χ hχ h1)) :=
  @Zeta23.Tail.prop_tail (chiZeroConfig χ hχ h1)

end Generic
end GRHWeil
end SIDEExplicitFormula
